nameOverride: ""
fullnameOverride: ""

application:
  reloader: false
  replicaCount: 1
  revisionHistoryLimit: 3
  podAnnotations: {}
  # prometheus.io/scrape: "true"
  # prometheus.io/path: "/metrics"
  # prometheus.io/port: "80"
  imagePullSecrets: []
  # - name: mySecret
  image:
    repository: openresty/openresty
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  probes:
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  # Service type ClusterIP and NodePort
  type: NodePort
  port: 80
  name: "proxy"
  nodePort: "32002"

ingress:
  enabled: true
  className: "system-ingress"
  annotations:
    certmanager.k8s.io/cluster-issuer: monitoring-issuer
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "application.zavaruev.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - application
      secretName: chart-example-tls

conf:
  default: |
    server {
      listen       80;
      server_name  localhost;
      location / {
          root   /usr/local/openresty/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/local/openresty/nginx/html;
      }
    }

html:
  index: |
    <html>
    <head>
        <title>Hello, Ivan Zavaruev</title>
        <meta charset="UTF-8">
    </head>
    <body>
      <h1>Hello Ivan Zavaruev</h1>
    </body>
    </html>
  50x: |
    <!DOCTYPE html>
    <html>
    <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <title>Error</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>An error occurred.</h1>
    <p>Sorry, the page you are looking for is currently unavailable.<br/>
    Please try again later.</p>
    </body>
    </html>

#===================================================
# Default values for openresty-art.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
