fullnameOverride: art

application:
  reloader: true
  probes:
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
  resources:
    limits:
      cpu: "0.2"
      memory: "400Mi"
    requests:
      cpu: "0.1"
      memory: "200Mi"

service:
  # Service type ClusterIP and NodePort
  type: NodePort
  name: "proxy"
  nodePort: 32002

ingress:
  enabled: true
  className: "system-ingress"
  annotations:
    certmanager.k8s.io/cluster-issuer: monitoring-issuer
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "application.zavaruev.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - application
      secretName: chart-example-tls